trigger:
- main

pool:
    vmImage: ubuntu-latest

stages:
    - stage: Test
      jobs:
      - job: Test
        steps:
            - script: echo testing app
    
    - stage: deployUS1 # this stage runs after test
      dependsOn: Test       
      jobs:
      - job: deploy_us1
        steps:
            - script: echo deploying to US1

    - stage: deployUS2 # this stage runs after DeployUS1
      dependsOn: Test  
      jobs:
      - job: deploy_us2
        steps:
            - script: echo deploying to deployUS2
    
    - stage: deployEurope # this stage runs after deployUS2
      dependsOn:
      - deployUS1
      - deployUS2
      jobs:
      - job: deploy_europe
        steps:
            - script: echo deploying to Europe

      



