trigger:
- main

pool:
    vmImage: ubuntu-latest

stages:
- stage: BuildApp
  displayName: Build Apps
  jobs:
  - job: BuildFrontendApp
    displayName: Build Frontend App
    steps:
    - script: echo building frontend App
      displayName: build frontend app
    - script: echo running unit tests for frontend app
      displayName: unit tests frontend

  - job: BuildBackendApp
    displayName: Build Backend App
    steps:
    - script: echo building backend 
      displayName: build backend app
    - script: echo running unit tests for backend app
      displayName: unit tests backend

- stage: DeployDev
  displayName: Deploy to Dev Environment
  jobs:
  - job: DeployFrontEndDev
    displayName: Deploy to Frontend Dev
    steps:
    - script: echo deploying frontend app to Dev
      displayName: deploy frontend app to DEV

  - job: DeployBackendDev
    displayName: Deploy Backend to DEV
    steps:
    - script: echo deploying backend app to DEV
      displayName: deploy backend to Dev
      
- stage: DeployProd
  displayName: Deploy to Prod Environment
  pool:
    vmImage: 'macOS-13'
  jobs:
  - job: DeployFrontEndProd
    displayName: Deploy Frontend to Prod
    steps:
        - script: echo deploying frontend app to Prod
          displayName: deploy frontend app to Prod

  - job: DeployBackendProd
    displayName: Deploy Backend to Prod
    pool: 
      vmImage: 'windows-2019'
    steps:
        - script: echo deploying backend app to Prod
          displayName: deploy backend app to PROD

      



